# Generated by Django 4.0.2 on 2022-02-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChoreoTool', '0005_userdata_displayname_userdata_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profilePic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
