# Generated by Django 4.0.2 on 2022-02-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChoreoTool', '0006_alter_userdata_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user',
            field=models.CharField(default='l', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
