# Generated by Django 4.0.2 on 2022-02-19 02:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChoreoTool', '0007_userdata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formations', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='formations',
            name='formations',
            field=models.CharField(max_length=200),
        ),
    ]
