# Generated by Django 4.0.2 on 2022-03-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChoreoTool', '0008_test_alter_formations_formations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='formationNum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
