# Generated by Django 4.0.2 on 2022-03-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChoreoTool', '0009_userdata_formationnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='formations',
            name='title',
            field=models.CharField(default='Title', max_length=100),
            preserve_default=False,
        ),
    ]
